# Site settings
title: JIATIAN SUN
email: jiatians@andrew.cmu.edu
url: https://jiatiansun.github.io
description: "I am expected share my projects"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/jiatiansun/

# Build settings
markdown: kramdown
permalink: pretty
